version: '3.4'
services:
  docker:
    container_name: docker
    image: docker:dind
    environment:
      DOCKER_TLS_CERTDIR: /certs
    ports:
      - "2376:2376"
    restart: always
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    command: --storage-driver=overlay2
    privileged: true

  jenkins-blueocean:
    container_name: jenkins-blueocean
    image: jenkinsci/blueocean:1.24.3
    links:
      - "docker"
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
    ports:
      - "8080:8080"
      - "50000:50000"
    restart: always
    volumes:
      - jenkins-docker-certs:/certs/client:ro
      - jenkins-data:/var/jenkins_home 

volumes:
  jenkins-docker-certs:
  jenkins-data:
