---
- hosts: dev
  become: true
  vars:
    domain: api.hobiku.demooke.com
    email: danajoo01@gmail.com
  tasks:
    - name: Create and Install Cert Using nginx Plugin
      command: "certbot --nginx -d  {{ domain }} -m {{ email }} --agree-tos --noninteractive --redirect"
