#################################################
# Install Nginx Certbot
#################################################
---
- hosts: dev
  become: true
  tasks:
    - name: update
      apt: update_cache=yes

    - name: Install Nginx
      apt: name=nginx state=latest

    - name: Install Nginx
      apt: name=python-certbot-nginx state=latest
