- hosts: all
  become: yes

  tasks:
    - name: create the admin user account
      user: name=admin append=yes state=present createhome=yes shell=/bin/bash

    - name: allow 'admin' to use sudo without needing a password
      lineinfile:
        dest: /etc/sudoers
        line: "admin ALL=(ALL) NOPASSWD: ALL"
        validate: "visudo -cf %s"

    - name: set up authorized keys for the admin user
      authorized_key: user=admin key="{{item}}"
      with_file:
        - ~/.ssh/id_rsa.pub
